name: Tusk Art Space Discovery
favicon: null
layout_spectrum: 0.9005
typography_spectrum: 0.59778
title: The Concept
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bdbdbd'
    - '#04376e'
    - '#4290b6'
    - '#d160c4'
  brandStrength: 0.75
  lightness: 0.2178242311347276
  saturation: 0.3125
  rhythmicContrast: 0.9675210462883115
purpose: []
