name: Tusk Art Space Discovery
favicon: null
layout_spectrum: 0.9005
typography_spectrum: 0.59778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0d0d'
    - '#8b7a69'
    - '#e2d7cc'
    - '#d8602c'
  brandStrength: 0.394040800165385
  lightness: 0.2178242311347276
  saturation: 0.3125
  rhythmicContrast: 0.9675210462883115
purpose: []
